# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  browserstackUser: $(BROWSERSTACK_USERNAME)
  browserstackKey: $(BROWSERSTACK_ACCESS_KEY)

steps:
- task: NodeTool@6.9.0 
  inputs:
    versionSpec: $(node_version)

- script: npm install
    