# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  user: $(BROWSERSTACK_USERNAME)
  key: $(BROWSERSTACK_ACCESS_KEY)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.15.1'
    checkLatest: false

- task: BrowserStackConfig@1
  inputs:
    BrowserStackServiceEndPoint: 'bss'
- script: npm install
- script: npm list | grep webdriver
- script: npm run single1
  displayName: 'Run a one-line script'
- task: PublishTestResults@2
- task: BrowserStackResults@1

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'